# Generated by Django 3.1.2 on 2020-10-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
