# Generated by Django 2.0.2 on 2020-10-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_profile_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
