# Generated by Django 2.0.2 on 2020-10-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0010_auto_20201019_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
