# Generated by Django 2.0.2 on 2020-10-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0012_auto_20201019_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='insta.Comment'),
        ),
    ]
