# Generated by Django 2.0.2 on 2020-10-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0019_auto_20201019_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comment',
        ),
    ]
