# Generated by Django 2.0.2 on 2020-10-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0021_comment_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
